### ISSUE TITLE
Updated MetaSRA with SRAdbV2

### ISSUE THREAD

**Issue by spadavec** [deweylab/MetaSRA-pipeline#271]
It appears that MetaSRA is mapped to SRAdb, but it appears that SRAdbV2 is the new version: https://github.com/seandavi/SRAdbV2

Can MetaSRA be run against this new version?

**Comment by mbernste** [comment]
Thanks for your inquiry. It looks like this new version facilitates querying the SRA's metadata, but it is unclear if the content of the underlying database has changed between this version and the previous version. Do you know if there is metadata included in this version that differs from the original? I assume that they are hitting the same backend database. If not, I am hesitant to change the MetaSRA's data source given that this package is not yet published and the author states, "This project is a work-in-progress."  However, I'm happy to discuss it!
